/*
 * Configuration.
 */

// Fetch.
export const FETCH_CONFIGURATION = 'FETCH_CONFIGURATION';
export const FETCH_CONFIGURATION_PENDING = 'FETCH_CONFIGURATION_PENDING';
export const FETCH_CONFIGURATION_REJECTED = 'FETCH_CONFIGURATION_REJECTED';
export const FETCH_CONFIGURATION_FULFILLED = 'FETCH_CONFIGURATION_FULFILLED';

/*
 * Deployments.
 */
export const OPEN_DEPLOYMENT = 'OPEN_DEPLOYMENT';
export const CLEAR_DEPLOYMENT = 'CLEAR_DEPLOYMENT';

// Fetch.
export const FETCH_DEPLOYMENTS = 'FETCH_DEPLOYMENTS';
export const FETCH_DEPLOYMENTS_PENDING = 'FETCH_DEPLOYMENTS_PENDING';
export const FETCH_DEPLOYMENTS_REJECTED = 'FETCH_DEPLOYMENTS_REJECTED';
export const FETCH_DEPLOYMENTS_FULFILLED = 'FETCH_DEPLOYMENTS_FULFILLED';

// Run.
export const RUN_DEPLOYMENT = 'RUN_DEPLOYMENT';
export const RUN_DEPLOYMENT_PENDING = 'RUN_DEPLOYMENT_PENDING';
export const RUN_DEPLOYMENT_REJECTED = 'RUN_DEPLOYMENT_REJECTED';
export const RUN_DEPLOYMENT_FULFILLED = 'RUN_DEPLOYMENT_FULFILLED';

/*
 * Auth.
 */

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
