/*
 * Deployments.
 */

// Fetch.
export const FETCH_DEPLOYMENTS = 'FETCH_DEPLOYMENTS';
export const FETCH_DEPLOYMENTS_PENDING = 'FETCH_DEPLOYMENTS_PENDING';
export const FETCH_DEPLOYMENTS_REJECTED = 'FETCH_DEPLOYMENTS_REJECTED';
export const FETCH_DEPLOYMENTS_FULFILLED = 'FETCH_DEPLOYMENTS_FULFILLED';
