/*
 * Deployments.
 */

// Fetch.
export const FETCH_DEPLOYMENTS = 'FETCH_DEPLOYMENTS';
export const FETCH_DEPLOYMENTS_PENDING = 'FETCH_DEPLOYMENTS_PENDING';
export const FETCH_DEPLOYMENTS_REJECTED = 'FETCH_DEPLOYMENTS_REJECTED';
export const FETCH_DEPLOYMENTS_FULFILLED = 'FETCH_DEPLOYMENTS_FULFILLED';

/*
 * Auth.
 */

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
